### ISSUE TITLE
Consider any attribute or TXT record additions required to support BCP-003-02

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-discovery-registration#101]
BCP-003-02 adds a requirement to pass Authorization headers in requests. These could be required to read/write IS-04 resources on Nodes/Registries, or could be required to interact with services/controls which are advertised from IS-04. The requirement to include an Authorization token may be deployment specific, and may only be required for certain aspects of a deployment.

We should consider whether this should be flagged via DNS-SD TXT records prior to interacting with the APIs (may not be possible for the Node API directly), and whether an attribute should be added to service/control advertisements to indicate any Authorization requirements. The alternative is that this is pre-configured across a deployment in a static fashion, but this may limit flexibility.

**Comment by andrewbonney** [comment]
I'd propose adding an 'api_auth' DNS-SD TXT record for IS-04 which could be 'true' or 'false' (mandated lower case as these are strings). This applies to both registries and Nodes (only where mDNS is implemented for the latter).

Within Node '/self', the 'api' object could have an 'authorization' boolean added to it. This could be optional or mandatory, with a default of false if optional.

Similarly, within Node 'services' and Device 'controls' an 'authorization' boolean could be added. This could be optional or mandatory, with a default of false if optional.

Finally, within Query API 'subscriptions' each could have an 'authorization' boolean added. This could be optional or mandatory, with a default of false if optional. The client performing a POST is unlikely to have a choice in what this value is set to (as we've found for the existing use of 'secure'). It's also unlikely that this value would differ from what was required to interact with the RESTful Query API and discovered via DNS-SD TXT records.

I'm avoiding use of 'secure' here as this is used for TLS elsewhere and is a little ambiguous. Any servers or clients which only implement earlier versions and haven't been updated would be unable to support authorization anyway, so their inability to observe these added values wouldn't be an issue, they'd simply receive a 401 when interacting with resources.

**Comment by garethsb** [comment]
That's pretty much what I was thinking too. 👍 

In the Node (/self) resource, did you mean that the 'authorization' boolean would be added under each individual endpoint? While it may not make a lot of sense for Nodes to have some 'http' endpoints, some 'https' endpoints without auth, and some with auth, adding it there would be consistent with 'protocol' being in each endpoint?

**Comment by andrewbonney** [comment]
Yes, agreed. It's certainly possible you could run different interfaces in different modes, so whilst unlikely we should support it.

**Comment by garethsb** [comment]
OK, all agreed then.

What about other places we may have HTTPS/WSS/Secure MQTT connection info/URLs?

IS-04 Node (deprecated) `href`
IS-04 Sender `manifest_href`
IS-05 WebSocket `connection_uri`
IS-05 MQTT `{destination,source}_{host,port}`

It gets tempting to say clients should just assume the auth/no-auth will be the same as the current API, but I think we're arguing against that sort of thing e.g. in https://github.com/AMWA-TV/nmos-event-tally/pull/57 and https://github.com/AMWA-TV/nmos-event-tally/issues/54#issuecomment-502349890 (https://github.com/AMWA-TV/nmos-device-connection-management/issues/80#issuecomment-502349318).

We're not currently going so far as to indicate what scopes (I think I mean scopes not claims?) might be required at any of those endpoints, and they may well be different than the current API, so maybe even indicating auth/no-auth all over the place isn't necessary?

**Comment by andrewbonney** [comment]
> IS-04 Node (deprecated) `href`

Seems unnecessary to handle as it's deprecated

> IS-04 Sender `manifest_href`

Whilst not deprecated the preferred location to use would be IS-05's transportfile, so I suggest we leave this to IS-05.

> IS-05 WebSocket `connection_uri`
> IS-05 MQTT `{destination,source}_{host,port}`

Unsure on these. Again it would be nice to be explicit if we can.

> We're not currently going so far as to indicate what scopes (I think I mean scopes not claims?) might be required at any of those endpoints, and they may well be different than the current API, so maybe even indicating auth/no-auth all over the place isn't necessary?

It could be either scopes or claims I suspect dependent on the context, but either way I'd expect the server which implements authorization to have a standardised expectation of what it should receive, and the client having identified that a given API (IS-04/IS-05/other) requires authorization should know how to handle things in that specific case.

**Comment by garethsb** [comment]
Right. And we shouldn't just be relying on clients to deal with `401 Unauthorized` (meaning un-_authenticated_)?

**Comment by andrewbonney** [comment]
That's the theory. We could just rely upon this, but dependent on how the behaviour and external configuration worked out this could result in delays as requests were re-attempted and tokens sought.

**Comment by garethsb** [comment]
Yep, OK, just checking I was on the right page.

I think we're saying places which are an 'entry point' to the ecosystem, like DNS-SD, or places which are strong boundaries in the system, like Node `services`, it makes sense to advertise whether or not authentication is required.

Some may argue that more tightly coupled APIs like Device `controls`, Sender `manifest_href` and /transportfile redirects, and `connection_uri` and possibly MQTT broker transport params, could reasonably all rely on an **ass**umption. But it's not clear cut as I'm aware of e.g. implementations serving transport files from legacy interfaces, so coupling is implementation-specific.

If we were to go the other way and _not_ advertise whether or not authentication is required anywhere, we could recommended client behaviour to try with/without auth based on external configuration or 'recent experience' with other APIs in the system, to reduce the number of re-attempts?
