### ISSUE TITLE
Requirement for DNS-SD 'TXT 'records

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-discovery-registration#11]
[3.0 Discovery](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.1.x/docs/3.0.%20Discovery.md) says 

> Advertisements of the above types **may** be accompanied by DNS TXT records as specified within the API RAML documentation.

[2.0 APIs - API Paths](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.1.x/docs/2.0.%20APIs.md#api-paths) says

> API clients using DNS-SD for API discovery **SHOULD** construct these paths by making use of the TXT records 'api_proto' and 'api_ver', along with addresses and ports resolved via DNS-SD.
> [...]
> Where protocol and versioning data is not available, clients **MAY** assume a v1.0 API, which operates via the 'http' protocol only.

On the other hand, e.g. the [RegistrationAPI.raml](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.1.x/APIs/RegistrationAPI.raml#L25) says:

> The DNS-SD advertisement **MUST** be accompanied by a TXT record of name 'api\_proto' [etc.]

In each case the **bold**  is mine, but capitalization from the source, presumably RFC2119 terms where capitalized, but there seems to be some difference of opinion as to whether the TXT records are required, or whether "api_proto" = "http", "api_ver" = "v1.0" (and "pri" = max_int?) is assumed if the TXT records are not present.

**Comment by andrewbonney** [comment]
The api_proto and api_ver TXT records were only introduced in v1.1. It is a requirement that they are present from v1.1 onwards (hence the MUST), but there can be no guarantee that a v1.0 implementation would have them (hence the MAY assumption).

**Comment by garethsb** [comment]
Thanks @andrewbonney, that makes sense. The "pri" record was REQUIRED in v1.0 however. For clarity, I think it would be worth avoiding uses of RFC2119 terms even in lowercase in the documentation. E.g. in the first sentence I quoted, we could change 'may be' to 'are'?

**Comment by andrewbonney** [comment]
I've updated the example you've given in a local copy and will update here once that's published. I'm hoping to push a couple of other documentation changes which have been brought up in the next week or so.

I'm happy to incorporate any other specific changes at the same time, but I'm afraid I can't dedicate the time to identifying other areas requiring changes at present.

**Comment by andrewbonney** [comment]
Marking this as resolved now that the docs commit has been merged, but please re-open or create a new issue if there are any remaining issues.
