### ISSUE TITLE
Broken links on 4.2._Behaviour_-_Querying.html 

### ISSUE THREAD

**Issue by peterbrightwell** [AMWA-TV/nmos-discovery-registration#135]
Simon R reports that the two links in the Websocket protocol don't work for the GitHub pages render.  

The first will be because we don't have a GitHub pages render of the old content model repo, and probably should be changed to point to MS-04.

The second is because the rendered JSON is now one level down in "resolved/" or "with-refs/" so that needs addressing in fix-links.sh.

**Comment by peterbrightwell** [comment]
The second issue is now fixed (https://github.com/AMWA-TV/nmos-doc-build-scripts/commit/cfb4f08c2a4afd82cf12663424cf96eb6953e408).

The first one would need to wait for the next point release (my preference), or we do github pages for nmos-content-model, and/or I put in a temporary hack to workaround.

**Comment by andrewbonney** [comment]
@peterbrightwell can this be closed now that the MS-04 link has been added?

**Comment by peterbrightwell** [comment]
Yes
