### ISSUE TITLE
Minor error in regex for source_audio schema

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-discovery-registration#139]
The current regex for Numbered Source Channel has a small error, currently only allowing NSC001-127. 

This should be NSC001-NSC128 (or NSC000-NSC127).

As 'Undefined Channel' ranges from U01-U64 I assume we want the first version (NSC001-NSC128).

**Comment by garethsb** [comment]
[VSF TR-03](http://www.videoservicesforum.org/download/technical_recommendations/VSF_TR-03_2015-11-12.pdf) is the source specification, and it says:

"NSC[CHNUM] - Numbered Source Channel [CHNUM] . A single channel of audio
that is ordered between 001 and 127 and is intended to play out in a Discrete Numbered
Sources Soundfield Group; for example NSC025."

**Comment by jasperpeeters** [comment]
You are right, the spec is clear on that. 
I always automatically assumed a 2^X number....

**Comment by garethsb** [comment]
We all look at previous specs and wonder what were they thinking?

![Standards - xkcd](https://imgs.xkcd.com/comics/standards.png)
