### ISSUE TITLE
GMID with capital letters

### ISSUE THREAD

**Issue by grmph555** [AMWA-TV/nmos-discovery-registration#144]
When the Grandmaster Clock ID is referenced in the SDP, the formatting needs to follow RFC 7273 and RFC 5234 subsequently, meaning that the GMID is written with capital letters.
Should IS-04 follow the same reference?

https://github.com/AMWA-TV/nmos-discovery-registration/blob/31ee9894ac55fb00b67201bce5c3f8275874c314/APIs/schemas/clock_ptp.json#L41

**Comment by garethsb** [comment]
Potentially should have done, but a bit late now without a backwards-incompatible change. Similar vagaries in DID/SDID formatting.

**Comment by andrewbonney** [comment]
Agreed, as this would be a major breaking change I don't think it's something that could be resolved until a v2.0.
