### ISSUE TITLE
Audio receiver nr of channels

### ISSUE THREAD

**Issue by wsneijers** [AMWA-TV/nmos-discovery-registration#147]
We have products that do not support an arbitrary amount of audio channels. For us now either 8/16/64 channels. However there seems to be now way to express this in the current IS-04/IS-05 API. This will go wrong, for example, with the [testing tool](https://github.com/AMWA-TV/nmos-testing) suite IS-05 Interaction with IS-04 test 18. Which will test with 2 channel SDP files.

**Comment by andrewbonney** [comment]
This sounds like useful input to #89. The testing tool issue sounds slightly different and may (in the worst case) require us to add a configuration parameter. Could you perhaps open a separate issue there for that?

**Comment by wsneijers** [comment]
Thanks for the quick reply! Agreed, sounds similar. I will create an issue on the nmos-testing repo for this.

**Comment by garethsb** [comment]
Yep, that's a good data point for the future `caps` work that we are keen to get off the ground, and suggests in this instance that e.g. `min_channels`, `max_channels`, would not be sufficiently expressive.

**Comment by garethsb** [comment]
Testing issue dealt with, after https://github.com/AMWA-TV/nmos-testing/issues/494
Receiver Capabilities activity now started.
