### ISSUE TITLE
Trailing slash policy is not clear enough

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-discovery-registration#15]
The trailing slash policy for the APIs is described here: https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/docs/2.0.%20APIs.md#urls-approach-to-trailing-slashes. This describes client behaviour but fails to make important observations about server implementations as they have been tested at workshops.

A server implementing the APIs MUST support GET/HEAD (ie. read related) operations to both the trailing slash and non-trailing slash version of each resource. One of these MAY produce a 301 response causing a redirect to the other if preferred.

A server implementing the APIs MUST support PUT/PATCH/POST/DELETE/OPTIONS (ie. write related) operations on the non-trailing slash version of each resource. The implementation MAY additionally support the same methods on the trailing slash version but this is not strictly required.

The latter of these cases is particularly important as clients which receive a 301 type response when performing a PUT/POST etc will trigger a GET once redirected rather than the originally intended method. As such we have standardised on using the non-trailing slash version for all 'write' requests to avoid ambiguity between implementations.

The documentation should be enhanced to reflect the above.

**Comment by garethsb** [comment]
> clients which receive a 301 type response when performing a PUT/POST etc will trigger a GET once redirected rather than the originally intended method.

That doesn't seem to be universal user agent behaviour, but the full horror is explained by https://tools.ietf.org/html/rfc7231#section-6.4 which suggests using _307 Temporary Redirect_ as a workaround and https://tools.ietf.org/html/rfc7538, which adds _308 Permanent Redirect_ to describe what we perhaps really want.

> A server implementing the APIs MUST support PUT/PATCH/POST/DELETE/OPTIONS (ie. write related) operations on the non-trailing slash version of each resource. The implementation MAY additionally support the same methods on the trailing slash version but this is not strictly required.

As mentioned in sony/nmos-cpp#1, if your proposal were adopted into the spec, what do you feel about the correct response to the Registration API base URL should be? https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/examples/registrationapi-v1.1-base-get-200.json currently has trailing slashes.

**Comment by andrewbonney** [comment]
Yes, the mixed interpretation of redirects is why this issue comes up at all really. I've got a variant of the text I originally proposed drafted locally but I'm not quite happy with it. I'm trying to get most of these documentation issues sorted at present as they're rather building up and the sooner they're included in releases the better. I'll have PRs for review shortly.

I'd agree that the returned response is non-ideal given the paths used to make requests, but any changes to this would be breaking and as such require a major version change. It's perhaps something we should record separately for review with a milestone of v2.0.
