### ISSUE TITLE
"push-based transports" and "pull-based transports"

### ISSUE THREAD

**Issue by ghost** [AMWA-TV/nmos-discovery-registration#167]
Hi!

What is exactly the meaning of "push-based transports" and "pull-based transports" mentioned in the [node behaviour](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/4.3.%20Behaviour%20-%20Nodes.md)?

Also, in the next paragraph:

> For push-based transports the Receiver interface_bindings SHOULD contain a single network interface unless a redundancy mechanism such as ST 2022-7 is in use, in which case each 'leg' SHOULD have its matching interface listed. Where the redundancy mechanism receives more than one copy of the stream via the same interface, that interface SHOULD be listed a corresponding number of times. For push-based transports the Receiver interface_bindings SHOULD list a single interface through which content is being consumed.

"push-based transports" is mentioned in all cases, perhaps "pull-based transports" is missing?

Thanks in advance.

Victor.

**Comment by peterbrightwell** [comment]
"Push-based" means the Sender controls when data is put onto the network.  This is the case for RTP which is currently where NMOS is used most. "Pull-based" means the Receiver asks for data, such as happens with protocols like DASH where the Receiver uses HTTP GET, but I'm not aware of any requirement to specify `interface_bindings` in such cases. 

Perhaps "such as RTP" could be added here to help?

**Comment by ghost** [comment]
Thanks for the explanation.

But this paragraph is still confusing (at least for me).

> For push-based transports the Receiver interface_bindings SHOULD contain a single network interface unless a redundancy mechanism such as ST 2022-7 is in use, in which case each 'leg' SHOULD have its matching interface listed. Where the redundancy mechanism receives more than one copy of the stream via the same interface, that interface SHOULD be listed a corresponding number of times. For push-based transports the Receiver interface_bindings SHOULD list a single interface through which content is being consumed.

Maybe 

> For PULL-based transports the Receiver interface_bindings SHOULD list a single interface through which content is being consumed.

instead of

> For PUSH-based transports the Receiver interface_bindings SHOULD list a single interface through which content is being consumed.

was intended?

Thanks in advance.

Victor.

**Comment by garethsb** [comment]
Yes, the last sentence is either redundant with the first sentence or pull was intended. I think you're right.

**Comment by ghost** [comment]
Thanks!
