### ISSUE TITLE
Confusing description of "subscription" in Sender schema

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-discovery-registration#170]
Hello!

`subscription` property of [Sender schema](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/APIs/schemas/sender.json) is described as `unicast only` which may be understood as that this property should be omitted or its fields set to `null`/`false` in multicast.

https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/4.3.%20Behaviour%20-%20Nodes.md#senders states that only `receiver_id` property of `subscription` object MUST be `null` in multicast when `active` MUST always reflect the actual state.

Does this change seem clarifying the things? https://github.com/N-Nagorny/nmos-discovery-registration/commit/c8a203ad4805e96c2d9a333e4cf0c26595a2fc78

**Comment by garethsb** [comment]
Agreed, your proposed change makes sense

**Comment by prince-chrismc** [comment]
👍

**Comment by peterbrightwell** [comment]
Closed on Incubator call 2021-06-23
