### ISSUE TITLE
"chassis_id" and "port_id" under node.json

### ISSUE THREAD

**Issue by ghost** [AMWA-TV/nmos-discovery-registration#172]
Hi.

The `interfaces` property description from `node.json` says: 

> Network interfaces made available to devices owned by this Node. Port IDs and Chassis IDs are used to inform topology discovery via IS-06, and require that interfaces implement ARP at a minimum, and ideally LLDP.

What if we are not implementing IS-06? For `chassis_id`, `null` is an option but it does not seem to be the case for `port_id`.

**Comment by garethsb** [comment]
The spec requires interfaces to implement [Address Resolution Protocol (ARP)](https://study-ccna.com/arp/) at a minimum, and you need to be able to expose via the NMOS Node resource what MAC address each interface has (as the `port_id`).
