### ISSUE TITLE
Question re: grain_rate in -30 and -31 audio Flows

### ISSUE THREAD

**Issue by duncwebb** [AMWA-TV/nmos-discovery-registration#173]
Reading through the spec and JSON schemas, grain_rate in Flow objects is defined as:

"Flows are composed of sequences of Grains. A Grain represents an element of Essence or other data associated with a specific time, such as a frame, a group of consecutive audio samples, or captions."

This would seem to distinguish sample rate (an audio specific characteristic) from grain rate. Would it be correct to interpret this such that a grain in the context of audio is a packet containing a group of consecutive audio samples associated with a specific time. So a pTime of 1ms would be a grain rate of 1/1000 and a pTime of 125us would be a grain rate of 1/8000. Or am I way off the mark here? I've looked at some other NMOS nodes that publish audio flows and they have grain rates that look like video frame rates. If there's no associated video flow though this wouldn't make any sense.

**Comment by garethsb** [comment]
See e.g. https://github.com/AMWA-TV/nmos-sink-metadata-processing/pull/16#issuecomment-853718166 for links to previous discussion related to `grain_rate` for audio Flows. In that comment, one of the options I outlined was to do as you suggest and use _1/packet time_, though I identified the wrinkle that a Flow may theoretically be transmitted by multiple Senders with different packet times. FWIW, as of https://github.com/AMWA-TV/nmos-testing/pull/521, the specific value of audio Flows' `grain_rate` is no longer tested.

**Comment by peterbrightwell** [comment]
Needs a clarification.
Architecture Review Group review: place on backlog

**Comment by cristian-recoseanu** [comment]
Previous discussion offered some options regarding possible values: https://github.com/AMWA-TV/is-04/issues/173#issuecomment-873097737.
Also, as previously mentioned https://github.com/AMWA-TV/nmos-testing no longer performs checks on grain_rate for audio Flows.
