### ISSUE TITLE
Can Sender exist without a Flow?

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-discovery-registration#176]
[Starting from v1.1](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/6.0.%20Upgrade%20Path.md#affected-keys-from-v11) `flow_id` can be `null` but Data Model [shows](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/images/class.png) that Sender always have one Flow. Could anyone answer whether Sender without an associated Flow is a valid case?

**Comment by garethsb** [comment]
See https://github.com/AMWA-TV/nmos-discovery-registration/pull/4.

> Permit ʼnullʼ flow_id against a Sender in order to allow advertisement before internal device routing has occurred

So I think it's just that the diagram didn't get updated.

**Comment by prince-chrismc** [comment]
I was not able to find any text or example... the only spot is the change log... perhaps this feature needs to be better document? Several controller require a flow/source to work.

**Comment by garethsb** [comment]
Agreed, the Upgrade Path mention and the schema itself allowing `null` aren't really enough. It'd certainly make sense to (a) fix the Data Model diagram, (b) add some words like those from the original PR to the `description` at https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/APIs/schemas/sender.json#L26, and (c) to add a test for this in the Client Testing effort (👀 @jonathan-r-thorpe)
