### ISSUE TITLE
Does uDNS only configuration over-ride requirement for a v1.2 Node to make mDNS announcements?

### ISSUE THREAD

**Issue by matthewdicken** [AMWA-TV/nmos-discovery-registration#185]
It appears that a node can be set to unicast or multicast only service discovery:
https://specs.amwa.tv/is-04/releases/v1.2.2/docs/3.0._Discovery.html
"‘Peer to Peer’ mode only supports multicast operation. Nodes may optionally be configured to support just one of unicast or multicast service discovery"

However, if a node advertises a v1.2 Node API, support for P2P mode is mandatory: 
https://specs.amwa.tv/is-04/releases/v1.2.2/docs/3.2._Discovery_-_Peer_to_Peer_Operation.html
The following pre-requisites are mandatory [...] to permit peer to peer discovery:
* All Nodes advertise their presence via mDNS at all times
* In the absence of a network registry, all Nodes additionally advertise a series of mDNS TXT records 

So in the case of a node running in uDNS only mode and being registered under v1.2 of a registration API, does it still need to send mDNS announcements? Similarly, if running in P2P mode, should the node monitor for registry APIs over uDNS as well as mDNS?

**Comment by peterbrightwell** [comment]
Architecture Review Group review: place on backlog

**Comment by TheSaneWonko** [comment]
This issue was resolved in version 1.3 of the API, by making Node mDNS announces optional.

**Comment by garethsb** [comment]
As I understood it, the OP is pointing out that if a Node supports both v1.3 AND v1.2 it's not clear if mDNS is still optional. Is v1.3 clear on this?

**Comment by kierank** [comment]
It's also saying if a node has registered under unicast DNS in v1.2, does it still need to send multicast announcements?
