### ISSUE TITLE
Exponential Backoff retry is only required for Node registration or all the subresource registration

### ISSUE THREAD

**Issue by VenkateswaranJ** [AMWA-TV/nmos-discovery-registration#194]
Please let me know if it's not the right place to ask this question.

As per the node registration behaviour described herein [AWMA Nmos page](https://specs.amwa.tv/is-04/releases/v1.3.2/docs/Behaviour_-_Registration.html#node-encounters-http-500-or-other-5xx-inability-to-connect-or-a-timeout) we should retry to register the node if we get 5XX response with exponential backoff algorithm. Is it only applicable for registering a node or it's also applicable for registering subresources (like devices, sources, senders, receivers etc.,)?

What should be the node implementation behaviour when it tries to update one of its subresources (let's say device) to the registry and it receives a 5XX error due to a network issue, should it retry the update again with a backoff algorithm or just drop the update?

**Comment by garethsb** [comment]
Yes, if _any_ request (e.g. update to a Device) to the Registration API fails with a `5xx` server error, timeout or connection error, then the specified recovery strategy should be used. That is, to heartbeat with the new Registration API instance and after receiving a `200` OK to retry the failed registration request.

If a further `5xx` server error,  timeout or connection error is encountered during this recovery process, exponential back off is recommended. 

If a `4xx` client error is received, that's handled differently. For example, if a Device update gets a `400` Bad Request response, there's something wrong with the request and there's no point retrying it.

**Comment by VenkateswaranJ** [comment]
@garethsb appreciate your prompt response.

**Comment by garethsb** [comment]
@VenkateswaranJ, you're welcome - if you have any suggestion for clarifying the spec, let us know.
