### ISSUE TITLE
Do media_type(s) need to be IANA assigned

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-discovery-registration#195]
Discussed at the Ely workshop...

Flow `media_type` and Receiver `caps.media_types` (and the Parameter Constraint `urn:x-nmos:cap:format:media_type`) is defined everywhere as "IANA assigned".

E.g. https://github.com/AMWA-TV/is-04/blob/0c48726e537574915ed9ef6cf550cc4a9fb57a74/APIs/schemas/flow_video_coded.json#L15

Do we really need these to be IANA assigned, or do we accept commonly used values like `audio/AM824` and `video/SMPTE2022-6` which are well defined by SMPTE or other industry bodies but are not found in the [IANA Media Types Register](https://www.iana.org/assignments/media-types/media-types.xhtml)? If so, could we tweak the language slightly?

**Comment by peterbrightwell** [comment]
@AMWA-TV/nmos-architecture-review will be interested?

**Comment by peterbrightwell** [comment]
Architecture Review Group review: place on backlog

**Comment by TheSaneWonko** [comment]
Committed and published in IS-04 1.3.3
