### ISSUE TITLE
Refine Registration Behaviour / Error reporting for unknown references

### ISSUE THREAD

**Issue by Mantls** [AMWA-TV/nmos-discovery-registration#196]
By defining a seperate error response, preferably with a well defined error object in the response, for _undefined references_ (such as sources/flows etc) it'd be possible for nodes to more easily resolve missing resouces.

Instead of **400** a registration would then instead respond a registration that references an to the registry unknown resource id with - for example - **412 Precondition Failed**.

**Comment by garethsb** [comment]
Falling to register resources in the correct order seems like a logic error to be fixed during development,  not a runtime error which could be automatically recovered from?

FWIW, for debugging the problem, the nmos-cpp implementation includes error details on the `400` response that would identify this class of error.

**Comment by peterbrightwell** [comment]
Architecture Review Group review: closing
