### ISSUE TITLE
Is there a convention/preference for which IS-04 device-type to advertise?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-discovery-registration#202]
Is there a convention/preference for which IS-04 device-type to advertise?
Also, is there any consequence of having both device types in the same NMOS environment? i.e. should it be possible to route between them, etc?

- Asked by Matt Dicken on AMWA Workshops Slack.

**Comment by garethsb** [comment]
I haven't seen anyone do anything useful with Device type if I'm honest. I don't believe any Controller will bother looking at it.

Neither IS-04 nor https://specs.amwa.tv/nmos-parameter-registers/branches/main/device-types/ are very helpful.
And the new BCP-002-02 Device function tag is more flexible. https://specs.amwa.tv/bcp-002-02/releases/v1.0.0/docs/Overview.html#function

**Comment by peterbrightwell** [comment]
Architecture Review Group review: place on backlog

**Comment by TheSaneWonko** [comment]
As pointed out by @garethsb [BCP-002-02 Device function tag](https://specs.amwa.tv/bcp-002-02/latest/docs/Overview.html#function) should used going forward.
