### ISSUE TITLE
Add digital cinema colorspaces to video Flow schema

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-discovery-registration#23]
A request was made via the AMWA Basecamp to add support to signal digital cinema colorspaces (ACES) in https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/APIs/schemas/flow_video.json. At present only ITU colorspaces (starting BT...) are included.

The likely additions would be:
ST2065-1, ST2065-3, DCI-D65, DCI-D60

**Comment by andrewbonney** [comment]
Schemas have been relaxed for this in v1.3-dev. Agreed values for these types could be defined in the parameter registers as a result.

**Comment by garethsb** [comment]
I think this may be covered by reference to ST 2110-20 in the permitted values of `colorspace` in the [Flow Attributes](https://github.com/AMWA-TV/nmos-parameter-registers/tree/main/flow-attributes) parameter register.
