### ISSUE TITLE
Examples for v1.2 Node interfaces don't match the schema

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-discovery-registration#30]
The schema correctly uses dashes as separators for MAC addresses, but the examples are using colons which were used in an earlier development version of the spec.

See https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/examples/nodeapi-v1.1-self-get-200.json for example.

**Comment by sparkpunkd** [comment]
Thanks for the fix!
