### ISSUE TITLE
Conflicting audio flow schemas

### ISSUE THREAD

**Issue by cmannett85** [AMWA-TV/nmos-discovery-registration#32]
Consider a raw audio flow:

```
{
        "type": "flow",
        "data": {
            "id": "aa993cd9-d811-4191-91d1-2ef72575cbda",
            "version": "1:2",
            "label": "my flow",
            "description": "",
            "tags": {},
            "source_id": "c9d11fb8-e220-4b63-86e0-8b11a3d60de1",
            "device_id": "7a05e81a-69be-4e30-b24a-e23004ca8f65",
            "parents": [],
            "format": "urn:x-nmos:format:audio",
            "sample_rate": {
                "numerator": 48000
            },
            "media_type": "audio/L24",
            "bit_depth": 24
        }
}
```

This will pass schema validation.  Now let's make a slight change:

```
"media_type": "audio/L32",
```

This will fail, even though the new `media_type` passes its regex constraint.  It fails because it now also passes the coded audio flow schema, but the flow root schema (the one in `flow.json`) mandates a `oneOf` constraint for all flow types.

**Comment by andrewbonney** [comment]
Thanks for the report. Two straightforward options would be to change the top level to be an 'anyOf', or to add 'audio/L32' to the permitted enum for raw audio. Neither of these seem perfect as the former would make the validation less strict, and the latter still doesn't solve the root problem as there will be other media types for raw audio.

There are a number of alternative fixes which just require an extra file or two to change, but I don't think any are perfect as without a full list of media types which are considered 'raw', some will always end up falling into the 'coded' bucket.

**Comment by cmannett85** [comment]
What's the benefit of having a raw/coded distinction?  I ask because ~~there isn't~~ I can't find a property which actually defines _what_ the encoding is.

**Comment by andrewbonney** [comment]
The only reason for this is the inclusion of 'bit_depth' alongside the defined raw types, which wouldn't be relevant in the coded case. Otherwise the 'media_type' is the only means to characterise the audio Flow at present.
