### ISSUE TITLE
Registration API mdns service name too long

### ISSUE THREAD

**Issue by jameswestendorp** [AMWA-TV/nmos-discovery-registration#34]
RegistrationAPI.raml specifies an mDNS service type of "_nmos-registration".

According to RFC6763 Section 7.2, the maximum service name length for an mDNS advertisement is 16 characters when including the leading underscore, but "_nmos_registration" is 18 characters.

**Comment by andrewbonney** [comment]
Thanks for the report. We've been aware of this for a good while, but as changing it would be a breaking modification we've opted not to do so as yet. A shorter name could replace the current one as of a v2.0, or if there was a requirement to do so a shorter name could be introduced as a secondary advertisement alongside the existing one with a minor release.

**Comment by jameswestendorp** [comment]
ok, understood.

**Comment by sparkpunkd** [comment]
My team lost a day of development time tracking this down. In the interim, would it be possible to add a note to the docs?

**Comment by andrewbonney** [comment]
Absolutely. As usual a pull request would be appreciated, but I am in the process of tackling a number of documentation issues so if nothing arrives in the interim I'll deal with it as part of that.

**Comment by bgilmer77** [comment]
Created PR #39

**Comment by andrewbonney** [comment]
Docs on this are now merged in and will be backported to other minor release versions as appropriate. I'll leave this issue open though as the problem still needs to be resolved.

**Comment by garethsb** [comment]
Another data point:

Apple's mDNSResponder supports over-long service types _but only for the "local" domain_, i.e. not for unicast DNS-SD.

See [mDNSResponder-878.30.4/mDNSShared/uds_daemon.c](https://opensource.apple.com/source/mDNSResponder/mDNSResponder-878.30.4/mDNSShared/uds_daemon.c.auto.html) line 2568.

**Comment by andrewbonney** [comment]
Should be resolved by https://github.com/AMWA-TV/nmos-discovery-registration/pull/71 and https://github.com/AMWA-TV/nmos-discovery-registration/pull/77 once v1.3 is released.
