### ISSUE TITLE
Peer-to-peer operation is not required

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-discovery-registration#53]
From [Discovery: Registered Operation](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/3.1.%20Discovery%20-%20Registered%20Operation.md):

> If no Registration APIs are advertised on a network, the Node _should assume peer to peer operation unless configured otherwise._ The required TXT record advertisements for this mode are described in the Node API.

On the other hand, the [Node API](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/APIs/NodeAPI.raml) says:

> When a Node is unable to locate or successfully register with a Registration API it _MUST_ additionally advertise the following mDNS TXT records

Since the former sentence allows for nodes to *not* assume peer-to-peer operation, the extra TXT records should not be required.

**Comment by andrewbonney** [comment]
Should be resolved by https://github.com/AMWA-TV/nmos-discovery-registration/pull/75
