### ISSUE TITLE
Grain "creation_timestamp"

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-discovery-registration#54]
From the [NMOS Content Model Specification](https://github.com/AMWA-TV/nmos-content-model/blob/master/specifications/ContentModel.md):

> NMOS specifications constrain a Grain used for interchange /to have _exactly_ two TimeStamps (Origin and Sync).

However, the [queryapi-subscriptions-websocket.json schema](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/APIs/schemas/queryapi-subscriptions-websocket.json) additionally has "creation_timestamp".

Discuss.
;-)

**Comment by andrewbonney** [comment]
I'd suggest that as the Content Model docs are a work in progress and due for review this can be safely ignored for now. Anything which results in inconsistencies with a released version of the content model should be addressed in a future version, but we'd probably be better doing a more thorough analysis of that when a released version is available.

**Comment by garethsb** [comment]
OK. It would help if the schema didn't describe "origin_timestamp", "sync_timestamp" and "creation_timestamp" identically, or explained _why_ they are identical in the case of websocket grains.
