### ISSUE TITLE
File extension in "manifest_href"

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-discovery-registration#63]
_Minor documentation nit..._

It would seem to be reasonable for an implementation to have the 'manifest_href' of a Sender refer to the relevant IS-05 Connection API endpoint?

However, [APIs: Server Side Implementation Notes > Node API Senders: Use with RTP](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/2.3.%20APIs%20-%20Server%20Side%20Implementation%20Notes.md#node-api-senders-use-with-rtp) says:

> When using RTP for a sender, the 'manifest_href' must be an HTTP-accessible reference to an SDP file. As-per RFC 4566, SDP files advertised via web services should use a MIME type of 'application/sdp' _and a file extension of '.sdp'. [my emphasis]_

On the other hand, the [IS-05 Connection API /transportfile endpoint](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L273) is understandably extension-less (to leave the door open for other transport file formats).

RFC 4566 actually seems to only have a single mention of a file extension, [Section 8.1 The "application/sdp" Media Type](https://tools.ietf.org/html/rfc4566#section-8.1), which says:

> File extension(s): The extension ".sdp" is commonly used.

Since the Media Type in a web services context is more relevant than the file extension, I suggest dropping the reference to file extension in the IS-04 documentation, or explicitly allowing the extension-less case.

**Comment by andrewbonney** [comment]
I think I agree there. As the referenced RFC doesn't mandate this we probably shouldn't either, although use of the correct MIME type is probably still a good idea. I'll sort out a PR.

The question is whether this would affect anyone's existing implementation, and if so whether that's a major concern. Hopefully this will come out as part of the PR review process.

**Comment by nmosmachine** [comment]
+1 to this. If some implementations rely on the extension, best to identify that as a possible issue at this stage
