### ISSUE TITLE
flow_id in sender schema v1.0.x vs v1.1.x/v1.2.x

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-discovery-registration#67]
In **v1.1.x** and **v1.2.x** the ```flow_id``` of a sender can be ```null``` regarding the ```sender.json```-schema. However, in **v1.0.x** only a valid uuid is allowed.

How to deal with this regarding the output of the Query API?

E.g. registering a **v1.2** sender with ```flow_id: null```, what should be the QueryAPI output if I ```GET``` ```<...>/query/v1.0/senders```? 

Should this resource be ignored for the output or should the resource be displayed even if the output of the API is not perfectly valid regarding the current active schema? 

Both alternatives look a bit inconsistent in their own way..

**Comment by garethsb** [comment]
Here's the relevant bits of a previous e-mail exchange I had with @andrewbonney.

At 20 June 2017 17:09, @garethsb-sony wrote:
> How about the change that allows a Sender’s “flow_id” to be null in v1.1? When downgrading a v1.1 Sender with “flow_id”: null, what value should be used in a v1.0 representation of the Sender?

At 20 June 2017 17:14, @andrewbonney wrote:
> The Sender flow_id one is unfortunate and I hadn’t clocked it as an issue until now. I don’t have a good solution to that off the top of my head, and our implementation (whilst I don’t think it ever sets that to null) would certainly produce an output that isn’t technically v1.0 valid at present.

Our implementation (sony/nmos-cpp) does the same; the sender will have ``"flow_id": null``.

**Comment by andrewbonney** [comment]
I should add, I'd be happy for the guidance to be omitting the offending Senders if preferred. Either way we should add this case to the docs - I'd clearly failed to log it as an issue on here previously.

I doubt there will be a massive number of v1.0 Query API clients developed at this point, but we should still aim to have a consistent approach.

**Comment by andrewbonney** [comment]
I believe this was resolved by https://github.com/AMWA-TV/nmos-discovery-registration/pull/83 and will be resolved in the v1.2.x branch by https://github.com/AMWA-TV/nmos-discovery-registration/pull/91
