### ISSUE TITLE
API and example mismatch

### ISSUE THREAD

**Issue by dufourgilles** [AMWA-TV/nmos-discovery-registration#7]
From API we read : 
baseUri: http://example.api.com/x-nmos/**{version}/node**

But from example https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/examples/nodeapi-v1.0-receivertarget-put-request.json we see :

    "manifest_href": "http://172.29.176.142:12345/x-nmos/**node/v1.0**/self/pipelinemanager/run/pipeline/1/pipel/ipp_rtptx0c6d/misc/sdp/", 

So, which one is correct ?
nmos-ledger follows the example.

Thanks.

Gilles.

**Comment by andrewbonney** [comment]
Hi Gilles,
Thanks for spotting that. I've just pushed a fix which resolves it. The examples and docs in https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/docs/2.0.%20APIs.md show the correct path construction.

Cheers,
Andrew
