### ISSUE TITLE
Improve documentation for how to populate Sender/Receiver subscriptions

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-discovery-registration#76]
It isn't completely clear how a Sender/Receiver's subscribed ID should be set when the Sender or Receiver is in a 'parked' or unsubscribed state. Whilst the 'active' flag is the authoritative reference for this in v1.2+, in order to maintain backwards compatibility for v1.1/v1.0 the Receiver's subscription sender_id needs to be set to 'null' when it is not subscribed to anything. This docs omission was noted having implemented checks in the test suite.

**Comment by garethsb** [comment]
Docs fix could note the example of viewing a v1.2 Receiver through a Query API v1.1, which will strip the "active" attribute.

**Comment by andrewbonney** [comment]
This is being addressed as part of https://github.com/AMWA-TV/nmos-discovery-registration/pull/84
