### ISSUE TITLE
Query API pagination MUST be detected by clients

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-discovery-registration#79]
Currently, Query API pagination "SHOULD" be supported by implementations but MUST be detected by clients.

There's nothing in the RAML specification of the Query API to indicate that pagination is not required (see definition of the [paged trait](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/APIs/QueryAPI.raml#L25). The [APIs - Query Parameters - Pagination](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/2.5.%20APIs%20-%20Query%20Parameters.md#pagination) documentation does begin "Query APIs SHOULD support pagination..." however.

From the client's point of view this means that a simple Query API request to e.g. /x-nmos/query/v1.2/nodes (with no query parameters) can have two different meanings.

1. For a Query API which *doesn't* implement pagination, all nodes are returned in a single response
2. For a Query API which *does* implement pagination, only the first page of results is returned

This problem arises because pagination isn't 'opt in' from the client's point of view. This is quite different than the other optional API features, where the client has to make a different request to opt into the feature, e.g. ``query.downgrade``, ``query.rql``, ``query.ancestry_id``.

In the case of pagination, it is currently therefore critical that *the client* distinguish between these two cases by examining the response headers that are (I believe) required if pagination is implemented, e.g. ``X-Paging-Limit``.

Suggestions:

* Clarify in the RAML that the Query API traits are *all* currently optional (SHOULD or MAY)
* Clarify in the RAML, and the Query Parameters documentation, that clients currently MUST check the pagination response headers to distinguish a paginated response
* Add more tests for pagination in https://github.com/AMWA-TV/nmos-testing
* Think about how to automate tests for clients
* Think about whether to 'fix' this in some way in IS-04 v1.3+

**Comment by garethsb** [comment]
On a related note, we have previously discussed making support for paging also optional on the Node API, to facilitate scalable 'super-Nodes'.

**Comment by andrewbonney** [comment]
@garethsb-sony has this been adequately addressed via the PR and your own work in the test suite, or do you think something further is required?

**Comment by garethsb** [comment]
The test suite doesn't check clients at all.

So unfortunately, I think the PR words are the best we have right now.

I do wonder whether pagination should have been opt-in for clients.

I.e.

``/nodes?foo=bar`` with no ``paging`` parameters must return _all_ matching resources (even from a Query API that implements pagination), which may be unordered, but a response of (probably) 501 is permitted if that operation would be too intensive.

``/nodes?foo=bar&paging.limit=100`` would opt into the 'paging' trait specification and return the first 100 matching resources (or fewer, including if the server's maximum limit is less), ordered as specified.

The problem with this is that for clients that support pagination but don't know whether a Query API supports pagination, *either* have to try _without_ ``paging`` parameters, and then retry with if they get a 501, *or* try first _with_ ``paging`` parameters, and then retry without if they got a 501 from that (because v1.3+ implementations should return 501 if they don't support them...).

I can't immediately see how to fix that.

**Comment by andrewbonney** [comment]
Ok. As an opt-in mechanism would be a new feature for v1.3+ I'll add a new issue to document the thinking at least, then it's not forgotten about and can be re-visited if desired.
