### ISSUE TITLE
Add signalling for IS-07 data via Source attributes

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-discovery-registration#88]
As described in https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0.x/docs/4.0.%20Core%20models.md#2-is-04-highlights IS-07 requires an additional Source attribute. In order to add this we need to ensure that the 'urn:x-nmos:format:data' URN is accompanied by a defined way to differentiate between different types of 'data' (including but not limited to IS-07 and SDI ancillary). Consideration should be given to this mechanism's extensibility in order to avoid unnecessary future version increments.

**Comment by andrewbonney** [comment]
From previous discussions:

The existing URN could be subclassified (for example to urn:x-nmos:format:data.ancillary and urn:x-nmos:format:data.event), however this poses some problems. Whilst this usage of URNs is covered by the spec, most implementers likely perform exact matching on URNs, which makes backward compatibility more awkward. In addition, when performing basic queries which only support exact matches, it would be impossible to filter out all 'data' Sources/Flows. For these reasons we have generally avoided use of this mechanism beyond what is already defined (for the RTP transport type).

An alternative approach is to permit an additional attribute for Sources and/or Flows. Various options have been considered, but this could be as basic as 'data_type' (if restricting to the 'data' format) or 'sub_format' if aiming for something more generic. The value could then be something simple such as 'ancillary' or 'event', or could be namespaced in a similar way to Flow media_types, for example 'smpte/ancillary' and 'amwa/event'. Note that in these latter cases spec/standard numbers are intentionally not called out as these are often more tightly associated with specific byte ordering or packing which would not be appropriate as a Source attribute.

Any sub-formats or similar should be defined in the parameter registers, with just the basic pattern identified by the schemas in order to aid extensibility.

**Comment by garethsb** [comment]
I note that we already have a subclassification of "urn:x-nmos:format:data.event" in the "type" field of Query WebSocket message "grain".

**Comment by andrewbonney** [comment]
Ah yes. Which we should be careful of given that (at least at present) that message format doesn't match IS-07.

**Comment by andrewbonney** [comment]
An alternative potential solution to this (which would require further discussion with the IS-07 group).

The 'event_type' could be added to both the Source and the Flow as opposed to just the Source. This ensures that all of the metadata required to make decisions on whether a given Receiver can consume a Flow are held within the Flow itself. This may appear to duplicate things, but allows the event_type in the Source to identify that there is still common ground at that level (in the same way that the 'format' attribute is shared between Sources and Flows). In time these 'event_type' fields may be allowed to differ slightly, for example in the case where an IS-07 sensor Source can generate measurements with two different types of units, but each Flow has a specific unit.

There may still be an eventual requirement for an additional 'type' attribute, but this does at least allow a generic application/json Flow to be differentiated from a specific IS-07 application/json Flow.

**Comment by garethsb** [comment]
Do any of https://github.com/bbc/nmos-discovery-registration/pull/1, https://github.com/bbc/nmos-discovery-registration/pull/4, https://github.com/bbc/nmos-discovery-registration/pull/5 represent current thinking? Do any of these line up with what's currently in IS-07 [Core models - IS-04 highlights](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0.x/docs/4.0.%20Core%20models.md#2-is-04-highlights)? (I'm a bit lost...)

**Comment by andrewbonney** [comment]
I don't think so. I'll draft a fresh one.

There may be some elements of https://github.com/bbc/nmos-discovery-registration/pull/5 which are of use in discussing signalling of mux contents, but that's a separate topic.

**Comment by andrewbonney** [comment]
Added a new PR for discussion. It may require further fleshing out should we wish to merge it, but hopefully it will be sufficient to work through any issues: https://github.com/bbc/nmos-discovery-registration/pull/7
