### ISSUE TITLE
Missing unicast streaming sequence specification

### ISSUE THREAD

**Issue by gilson27** [AMWA-TV/nmos-discovery-registration#9]
In the figure https://raw.githubusercontent.com/AMWA-TV/nmos/master/images/connection-sequence.png,  
the destination node fetches SDP file, which, contains multicast streaming details of the sender. What should be the procedure for connection establishment, in the case of unicast media streaming?

**Comment by andrewbonney** [comment]
Hi,
The connection management capability included in this specification targets multicast only. Unicast may only be used at present if the Sender is set up out of band before performing the Receiver setup procedure.

Specification of a more fully featured connection management API is ongoing within the Networked Media Incubator project (http://www.amwa.tv / http://www.nmos.tv) and will be shared via a new GitHub repository once documentation is available.

Thanks

**Comment by gilson27** [comment]
Hi Andrew,
  Thanks for the quick reply. It would be better, if we add device configuration(e.g: network settings) and ptp configuration(e.g: ptp mode) as part of the NMOS API specification.

**Comment by andrewbonney** [comment]
Hi,
These are all potential subjects of future work. I should note however that the project doesn't aim to provide a universal mechanism to control everything about a device. At present these are most likely to be surfaced via a common status interface rather than something which could also change them.

Thanks

**Comment by gilson27** [comment]
Thanks @andrewbonney .
I'll get back to you in case of any doubts.
