### ISSUE TITLE
Query API deleting persistent subscriptions with open connections

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-discovery-registration#95]
[Query API Behaviour](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/4.2.%20Behaviour%20-%20Querying.md#query-api-behaviour) is quite clear about HTTP DELETE of non-persistent subscriptions. How about the case of attempting HTTP DELETE of a persistent subscription which has open WebSocket connections? Should this forcibly close the WebSockets? Or is HTTP DELETE forbidden until all connections are closed?

**Comment by andrewbonney** [comment]
My interpretation (and that of our implementation) is to forcibly close any open connections in this case. If that isn't controversial then a small docs update may be in order.

**Comment by garethsb** [comment]
That's how I've implemented it too (asynchronously).
